---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-gameserver-service-1
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  selector:
    ggj25-luis.service: "1"
  type: LoadBalancer
  ports:
  - name: http-port
    port: 30250
    protocol: TCP
    targetPort: 8080
  - name: game-port-udp
    port: 27050
    protocol: UDP
    targetPort: 7000
  - name: game-port-tcp
    port: 27050
    protocol: TCP
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-gameserver-service-2
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  selector:
    ggj25-luis.service: "2"
  type: LoadBalancer
  ports:
  - name: http-port
    port: 30251
    protocol: TCP
    targetPort: 8080
  - name: game-port-udp
    port: 27051
    protocol: UDP
    targetPort: 7000
  - name: game-port-tcp
    port: 27051
    protocol: TCP
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-gameserver-service-3
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  selector:
    ggj25-luis.service: "3"
  type: LoadBalancer
  ports:
  - name: http-port
    port: 30252
    protocol: TCP
    targetPort: 8080
  - name: game-port-udp
    port: 27052
    protocol: UDP
    targetPort: 7000
  - name: game-port-tcp
    port: 27052
    protocol: TCP
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-gameserver-service-4
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  selector:
    ggj25-luis.service: "4"
  type: LoadBalancer
  ports:
  - name: http-port
    port: 30253
    protocol: TCP
    targetPort: 8080
  - name: game-port-udp
    port: 27053
    protocol: UDP
    targetPort: 7000
  - name: game-port-tcp
    port: 27053
    protocol: TCP
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-gameserver-service-5
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  selector:
    ggj25-luis.service: "5"
  type: LoadBalancer
  ports:
  - name: http-port
    port: 30254
    protocol: TCP
    targetPort: 8080
  - name: game-port-udp
    port: 27054
    protocol: UDP
    targetPort: 7000
  - name: game-port-tcp
    port: 27054
    protocol: TCP
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-gameserver-service-6
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  selector:
    ggj25-luis.service: "6"
  type: LoadBalancer
  ports:
  - name: http-port
    port: 30255
    protocol: TCP
    targetPort: 8080
  - name: game-port-udp
    port: 27055
    protocol: UDP
    targetPort: 7000
  - name: game-port-tcp
    port: 27055
    protocol: TCP
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-gameserver-service-7
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  selector:
    ggj25-luis.service: "7"
  type: LoadBalancer
  ports:
  - name: http-port
    port: 30256
    protocol: TCP
    targetPort: 8080
  - name: game-port-udp
    port: 27056
    protocol: UDP
    targetPort: 7000
  - name: game-port-tcp
    port: 27056
    protocol: TCP
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-gameserver-service-8
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  selector:
    ggj25-luis.service: "8"
  type: LoadBalancer
  ports:
  - name: http-port
    port: 30257
    protocol: TCP
    targetPort: 8080
  - name: game-port-udp
    port: 27057
    protocol: UDP
    targetPort: 7000
  - name: game-port-tcp
    port: 27057
    protocol: TCP
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-gameserver-service-9
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  selector:
    ggj25-luis.service: "9"
  type: LoadBalancer
  ports:
  - name: http-port
    port: 30258
    protocol: TCP
    targetPort: 8080
  - name: game-port-udp
    port: 27058
    protocol: UDP
    targetPort: 7000
  - name: game-port-tcp
    port: 27058
    protocol: TCP
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-gameserver-service-10
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  selector:
    ggj25-luis.service: "10"
  type: LoadBalancer
  ports:
  - name: http-port
    port: 30259
    protocol: TCP
    targetPort: 8080
  - name: game-port-udp
    port: 27059
    protocol: UDP
    targetPort: 7000
  - name: game-port-tcp
    port: 27059
    protocol: TCP
    targetPort: 7000