apiVersion: apps/v1
kind: Deployment
metadata:
  name: ggj25-luis-nodejs
  namespace: ggj25-luis
spec:
  replicas: 1
  selector:
    matchLabels:
      helios.service: ggj25-luis-nodejs
  template:
    metadata:
      labels:
        helios.service: ggj25-luis-nodejs
        name: ggj25-luis-nodejs
    spec:
      containers:
      - name: ggj25-luis-nodejs
        image: 10.0.0.3:5000/ggj25/ggj25-luis-nodejs:${gitHash}
        ports:
        - containerPort: 3000
        - containerPort: 7776
      serviceAccountName: ggj25-luis
---
apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-nodejs
  namespace: ggj25-luis
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  ports:
  - name: http-port
    protocol: TCP
    port: 27045
    targetPort: 3000
  - name: lobby-port
    protocol: TCP
    port: 7780
    targetPort: 7776
  selector:
    helios.service: ggj25-luis-nodejs
  type: LoadBalancer