apiVersion: v1
kind: Service
metadata:
  name: ggj25-luis-nodejs-service
spec:
  selector:
    helios.service: ggj25-luis-nodejs
  type: LoadBalancer
  ports:
    - name: http-port
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: lobby-port
      protocol: TCP
      port: 7776
      targetPort: 7776
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ggj25-luis-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      helios.service: ggj25-luis-nodejs
  template:
    metadata:
      labels:
        helios.service: ggj25-luis-nodejs
        name: ggj25-luis-nodejs
    spec:
      containers:
      - name: ggj25-luis-nodejs
        image: 10.0.0.3:5000/ggj25/ggj25-luis-nodejs:${gitHash}
        ports:
        - containerPort: 3000
        - containerPort: 7776
      serviceAccountName: ggj25
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ggj25-luis-nodejs
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharedkey"
    metallb.universe.tf/address-pool: bifrost
spec:
  ports:
  - name: "http"
    port: 7780
    targetPort: 7776
  selector:
    app: smokeping
  type: LoadBalancer