
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  name: ggj25-luis
  namespace: ggj25-luis
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]